#UDB Config File

#Lives options
lives:
  #Can be hours or minutes
  banTimeType: hours

  #Ban time is either hours or minutes (look above).
  #336 Hours = 2 Weeks.
  #NOTE: Set to 0 for a perma-ban, and -1 for no ban.
  banTime: 336

  #Amount of lives a player is given when they first join
  firstLives: 3

