name: UDB
main: com.gmail.jython234.udb.UDBPlugin
version: 1.1-SNAPSHOT
depend: [Vault]

commands:
  udb:
    description: This is the root command for UDB.
    usage: /udb [operation]
    permission: udb.udb
    permission-message: "You don't have the permission udb.udb"

  udb-db:
    description: This is the database command for UDB.
    usage: /udb-db [operation]
    permission: udb.db.manage
    aliases: [db]
    permission-message: "You do not have the permission udb.db.manage"

permissions:
  udb.*:
    description: Gives access to all UDB commands and features.
    children:
      udb.udb: true
      udb.setlives: true
      udb.bypass: true
      udb.unban: true
      udb.db.*: true

  udb.db.*:
    description: Gives access to all UDB-DB features.
    children:
      udb.db.save: true
      udb.db.reload: true
      udb.db.manage: true

  udb.udb:
    description: Allows you to use the root UDB command.
    default: true

  udb.setlives:
    description: Allows you to set other player's lives.
    default: op

  udb.unban:
    description: Allows you to unban players.
    default: op

  udb.bypass:
    description: Allows you to bypass UDB bans (even if banning is enabled).
    default: false

  udb.db.save:
    description: Allows you to save the UDB database.
    default: op

  udb.db.reload:
    description: Allows you to re-load the UDB database (discards recent changes).
    default: op

  udb.db.manage:
    description: Manage the UDB database.
    default: op